language: python
python:
    - "3.7"
    - "3.8"
before_install:
    - pip install poetry
install:
    - poetry install
script:
    - poetry run python -m pytest --cov=snow --cov=tests --ignore venv
after_success:
    - codecov
